config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'insects#home'
  get 'insect', to: 'insects#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/insect.rb
class Insect < ApplicationRecord
  # has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/insects_controller.rb
class InsectsController < ApplicationController
  def home
  end

  def show
    place = params[:place]
    @insects = INSECTS.select { |insect| insect[:place] == place }
    @insect = @insects.sample
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/insects/home.html.erb
<%= render 'shared/header' %>

<div class="inner">
    <div class="contents">
        <h2 class="home-title">昆虫をつかまえにいきましょう。</h2>
        <h2 class="home-title">どこいく？</h2>
        <div class="flex jcc items">
            <div class="space">
                <a href="<%= insect_path(place: '雑木林') %>">
                    <p>雑木林</p>
                    <%= image_tag 'zokibayashi.jpg', class: 'space-img' %>
                </a>
            </div>
            <div class="space">
                <a href="<%= insect_path(place: '草原') %>">
                    <p>草原</p>
                    <%= image_tag 'sogenn.jpg', class: 'space-img' %>
                </a>
            </div>
            <div class="space">
                <a href="<%= insect_path(place: '河原') %>">
                    <p>河原</p>
                    <%= image_tag 'kawara.jpg', class: 'space-img' %>
                </a>
            </div>
        </div>
        <h2 class="desc-title">場所によってとれる昆虫が変わるよ！</h2>
        <p class="home-text">雑木林で15種類、草原で15種類、河原で15種類発見されている。虫じゃないのも見つかってるぞ！</p>
        <p>コンプリートできたらすごい！</p>
        <p>ただし、調査の途中なのでこれから発見される虫が増えていくかもしれない。</p>
        <h2 class="desc-title">使い方は簡単！</h2>
        <p class="home-text">雑木林、草原、河原のいずれかを押すとランダムに昆虫が表示されます。</p>
        <p>なかなか捕まえられないレアな昆虫もいるので、何度も出かけましょう！</p>
    </div>
</div>

<%= render 'shared/footer' %>

app/views/insects/show.html.erb
<%= render 'shared/header' %>
<div class="inner">
  <div class="contents">
    <h1 class="show-title"><%= @insect[:place] %>でつかまえたのは....</h1>
    <h1 class="show-title accent"><%= @insect[:name] %></h1>
    <div class="show-flex">
      <div class="show-img">
        <%= image_tag(@insect[:image_url], alt: @insect[:name]) %>
      </div>
      <div class="show-desc">
        <p><%= @insect[:description] %></p>
        <div class="share_btn">
          <%= link_to 'Xで共有する', "https://twitter.com/intent/tweet?url=https://insect-log.onrender.com&text=#{CGI.escape("#{@insect[:name]}を#{params[:place]}でつかまえたよ！みんなもインセクトログで昆虫探しの冒険に出かけよう！#インセクトログ")}", title: 'Xで共有する', target: '_blank', class: 'share' %>
        </div>
        <div class="reload">
          <button onclick="location.reload();" class="reload-button">もう一度つかまえにいく</button>
        </div>
      </div>
    </div>
  <div class="show-btn"><%= link_to '戻る', root_path, class: 'home-link' %></div>
  </div>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InsectLog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer>
    <div class="inner">
        <p class="copyright">© 2024 インセクトログ</p>
    </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="inner header-flex">
    <h1><%= link_to 'インセクトログ', root_path %></h1>
    <ul>
      <li><%= link_to 'ホーム', root_path %></li>
    </ul>
  </div>
</header>